version: "3.7"
services:
  router:
    image: decolua/9router:latest
    hostname: "router9"
    container_name: wpdews-9router
    restart: unless-stopped
    ports:
      - "20128:20128"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - DATA_DIR=/app/data
      - HOSTNAME=0.0.0.0
      - PORT=20128
